# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerA', models.CharField(max_length=120)),
                ('capacityA', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Class_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerB', models.CharField(max_length=120)),
                ('capacityB', models.IntegerField(default=40)),
            ],
        ),
    ]
