# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_a',
            name='capacityA',
        ),
        migrations.RemoveField(
            model_name='class_b',
            name='capacityB',
        ),
    ]
